version: "3.9"

services:
  scm2_frontend_jt:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./frontend/src:/usr/share/nginx/html
    depends_on:
      - scm2_backend_jt
    networks:
      - frontend

  scm2_backend_jt:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - scm2_db_jt
    networks:
      - frontend
      - backend

  scm2_db_jt:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
    volumes:
      - ./db/data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
