version: "3.9"

services:
  scm2-frontend-jt:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./frontend/src:/usr/share/nginx/html
      - ./frontend/config/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - scm2-backend-jt
    networks:
      - frontend

  scm2-backend-jt:
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /code
    volumes:
      - ./backend:/code
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - scm2-db-jt
    networks:
      - frontend
      - backend

  scm2-db-jt:
    image: postgres:15.1-alpine
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: user
      POSTGRES_DB: data
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/config/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

networks:
  frontend:
  backend:
