version: "3.9"

services:
  scm2_frontend_jt:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./frontend/src:/usr/share/nginx/html
      - ./frontend/config/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - scm2_backend_jt
    networks:
      - frontend

  scm2_backend_jt:
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /code
    volumes:
      - ./backend:/code
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - scm2_db_jt
    networks:
      - frontend
      - backend

  scm2_db_jt:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - backend

networks:
  frontend:
  backend:
