name: Frontend Image CI

on:
  push:
    branches: ["release", "beta", "develop"]

  workflow_dispatch:

jobs:
  build:
    if: github.ref == 'refs/heads/release' || github.ref == 'refs/heads/beta'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./frontend
          push: true
          # platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
          platforms: linux/amd64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/scm2_frontend:${{ github.ref_name }}-latest, ${{ secrets.DOCKERHUB_USERNAME }}/scm2_frontend:${{ github.ref_name }}-${{ github.sha }}
